# Generated by Django 4.1.6 on 2023-02-10 15:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('number', models.CharField(blank=True, max_length=512, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Остановка',
                'verbose_name_plural': 'Остановки',
            },
        ),
        migrations.CreateModel(
            name='CurrentStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_stop', to='routes.route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_stop', to='routes.station')),
            ],
            options={
                'verbose_name': 'Остановка маршрута',
                'verbose_name_plural': 'Остановки маршрутов',
            },
        ),
    ]
