# Generated by Django 3.2.17 on 2023-02-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='station',
            name='lon',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
